name:                sky-guidance
github:              "nalkuatov/sky-guidance"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- rio
- aeson
- mtl
- wai
- warp
- yaml
- template-haskell
- persistent
- persistent-template
- persistent-redis
- http-client
- servant-client
- servant-server

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- DataKinds
- TypeOperators
- FlexibleContexts

library:
  source-dirs: src

executables:
  sky-guidance-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sky-guidance

